version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
  
  graphql-server:
    image: hydra-kit:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.hydra
      context: ./
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - "4000:${GRAPHQL_SERVER_PORT}"
    depends_on: 
      - db
    command: ["yarn", "server:start:prod"]


  processor:
    image: hydra-kit:latest
    restart: unless-stopped
    build: 
      dockerfile: docker/Dockerfile.hydra
      context: ./
    env_file:
      - .env
    environment:
      - INDEXER_ENDPOINT_URL=http://indexer-api-gateway:4000/graphql
      - DB_HOST=db
      - PROCESSOR_POLL_INTERVAL=300
      - TYPEORM_HOST=db
      - DEBUG= index-builder:*
    depends_on:
      - indexer-api-gateway
    command: ["yarn", "processor:start"]
  
  indexer:
    image: joystream/hydra-indexer:latest
    restart: unless-stopped
    env_file:
      - .env 
    environment:
      - DB_HOST=db
      - DB_NAME=indexer-db
      - INDEXER_WORKERS=5
      - REDIS_URI=redis://redis:6379/0
      - DEBUG=index-builder:*
    depends_on: 
      - db
    command: > 
      sh -c "yarn db:bootstrap && yarn start:prod" 
  
  indexer-api-gateway:
    image: joystream/hydra-indexer-gateway:latest
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=indexer-db
      - WARTHOG_STARTER_DB_HOST=db 
      - WARTHOG_STARTER_DB_PASSWORD=${DB_PASS}
      - WARTHOG_STARTER_DB_PORT=${DB_PORT}
      - WARTHOG_STARTER_DB_USERNAME=${DB_USER}
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0 
      - PORT=4000
    ports:
      - "4001:4000"
    depends_on:
      - redis
      - db
      - indexer
    
  redis:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"